### ISSUE TITLE
1.Base install script renders OS useless

### ISSUE THREAD

**Issue by kennethrrosen** [a-barinov/liteqube#10]
I ran the install script within 1.Base, then attempted to run the install script from 2.Network, but received an error saying the disposable qvm wasn't installed. I rebooted the machine. Now I cannot access any VM, any dom0 application other than terminal, and the base uninstall script threw an error. I'm unable to use my system. Qvm-start from dom0 yields endless errors. Short of a fresh install, what are my options to recover my system?

**Comment by kennethrrosen** [comment]
Adding the error code from when I attempted to start sys-net
![Uploading IMG_20220911_235815_613.jpg…]()

**Comment by kennethrrosen** [comment]
![Uploading IMG_20220911_235815_613.jpg…]()

**Comment by a-barinov** [comment]
Similar situation happened to me once when Qubes OS root ran out of free space and /var/lib/qubes/qubes.xml got destroyed. If that's the case then just restore latest backup from /var/lib/qubes/backup and you,ll be fine.

**Comment by kennethrrosen** [comment]
I ended up doing fresh install and restoring from backup. How can I prevent on the next go around? After restore I'll try again.

**Comment by a-barinov** [comment]
Did you install from the latest release or from Master? I'm happy to run a test fresh install for you today to test the code paths, although still believe this was a qubes.xml corruption issue.

On the install you have, can you please provide the output of 'df' in dom0?

**Comment by kennethrrosen** [comment]
from the latest release

Filesystem                  1K-blocks    Used Available Use% Mounted on
devtmpfs                      1975360       0   1975360   0% /dev
tmpfs                         1996136       0   1996136   0% /dev/shm
tmpfs                         1996136    2816   1993320   1% /run
/dev/mapper/qubes_dom0-root  51421872 5240668  43837012  11% /
tmpfs                         1996136       0   1996136   0% /tmp
xenstore                      1996136     640   1995496   1% /var/lib/xenstored
/dev/nvme0n1p1                 996780  121860    806108  14% /boot
tmpfs                          399224      24    399200   1% /run/user/1000

**Comment by kennethrrosen** [comment]
I've run 1.Base install script, moved to 2.Network and receive this error:

ERROR: core-dvm NOT FOUND, PLEASE RUN BASE INSTALL

**Comment by a-barinov** [comment]
> from the latest release
> 
> Filesystem 1K-blocks Used Available Use% Mounted on devtmpfs 1975360 0 1975360 0% /dev tmpfs 1996136 0 1996136 0% /dev/shm tmpfs 1996136 2816 1993320 1% /run /dev/mapper/qubes_dom0-root 51421872 5240668 43837012 11% / tmpfs 1996136 0 1996136 0% /tmp xenstore 1996136 640 1995496 1% /var/lib/xenstored /dev/nvme0n1p1 996780 121860 806108 14% /boot tmpfs 399224 24 399200 1% /run/user/1000

Definitely not a free disk space issue (which caused metadata corruption once for me). I'll now check my commits to lib.sh since last release to see what can cause ill side effects.

**Comment by kennethrrosen** [comment]
appreciate it and sorry for the bother! standing by

**Comment by a-barinov** [comment]
Hopefully fixed by commit #e9b0886861aa46ba4cc4469c1488ed4694304ef1 pushed a minute ago. A pretty silly bug causing every created qube to be called 'core-sound'. Base installer was not touched for a while now so I expect no other surprises for you. And thanks for your patience!

**Comment by kennethrrosen** [comment]
> Hopefully fixed by commit #e9b0886861aa46ba4cc4469c1488ed4694304ef1 pushed a minute ago. A pretty silly bug causing every created qube to be called 'core-sound'. Base installer was not touched for a while now so I expect no other surprises for you. And thanks for your patience!

Success. Using litequbes as my base system now. Please let me know if I might assist with further testing.
