### ISSUE TITLE
[core-sound] Improvement Suggestion

### ISSUE THREAD

**Issue by lastcast** [a-barinov/liteqube#9]
Please consider changing this [script](https://github.com/a-barinov/liteqube/blob/main/7.Audio/default/debian-core/etc/protect/template.core-sound/config/liteqube-pulseaudio-daemon) to use `admin.vm.property.Get+audiovm` and `admin.vm.property.Get+xid` instead of `admin.vm.property.GetAll`.

**Comment by a-barinov** [comment]
Thanks for the idea! Today's commit fixes this, further simplifies systemd audio scripts, and also improves installer/uninstaller.
